language: cpp
compiler:
  - gcc
  - clang
script: sudo ./install.sh
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
before_script:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.55-thread-dev libboost1.55-system-dev libboost1.55-serialization-dev
  - sudo apt-get install -qq cmake sqlite3
