sudo: false
language: cpp
compiler:
  - gcc
#  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
#    - clang
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - PREFIX=$HOME/.local
  - export PATH=$PREFIX/bin:$PATH
install:
  - ./.install/boost.sh thread,system,serialization $PREFIX
  - ./.install/sqlite3.sh $PREFIX
  - pip install cpp-coveralls --user `whoami`
script: 
  - ./install.sh $PREFIX Debug
after_success: 
  - coveralls -e "include/Tools/SHA256.h" -e "include/Tools/sqlambda.h" -e "include/Tools/json.hpp" -e tests -E ".*lib.*" -E ".*usr.*" -E ".*boost.*" --gcov-options '\-lp' --gcov /usr/bin/gcov-4.8
