sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - sqlite3
    - gcc-4.8
    - g++-4.8
    - clang
script: ./install.sh ./
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
before_install:
  - wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.gz > /dev/null
  - tar xfz boost_1_58_0.tar.gz > /dev/null
  - cd boost_1_58_0
  - ./bootstrap.sh --with-libraries=thread,system,serialization > /dev/null
  - ./b2 --prefix=../ install > /dev/null
  - cd ..
  - dpkg -s sqlite3
  