language: cpp
compiler:
  - gcc
  - clang
script: sudo ./install.sh
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
before_script:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread1.55-dev libboost-system1.55-dev libboost-serialization1.55-dev
  - sudo apt-get install -qq cmake sqlite3
